### PR TITLE
Remove arrow function causing `this.resourcePath` to be undefined

### LINKED ISSUE #1: Arrow function overrides this and break this loader
I have try to setup this loader on my project running typescript, but it doesn't work properly.

Chrome logs shows that update is detected and considered as a hot module reload change, `reload()` function is called on [hot reload api](https://github.com/vuejs/vue-hot-reload-api), but it has no effect, the component is not updated with html template changes.

Any idea ? Maybe it's a hot reload api issue ...

### PR DESCRIPTION
**Pull request by Toilal**
Close #1

### CODE REVIEW

**Comment by ktsn** [comment]
Thanks!

**Comment by Toilal** [comment]
Thanks you too for the project.

I don't like `.vue` component files that much, and this plugin is really required to have a fast reload on development environment.

Can you perform a release soon with the fix ?

**Comment by Toilal** [comment]
Also there's a duplicate project here : https://github.com/jshmrtn/vue-hot-loader. Maybe we could tell this guy to join your project ?

I think your module is more robust because it checks there's a default export on the component file.

**Comment by ktsn** [comment]
I've released v0.1.1 with this fix.

Well, not sure about the collaboration. I actually just create this library as a small experiment and probably won't develop it actively so much. But PRs always welcome.

**Comment by Toilal** [comment]
Yes, I just found your other project vue-template-loader that seems to be a step beyond for what I need too :)

**Pull request merged**
